server:
  port: 8081

spring:
  config:
    import: "configserver:http://localhost:8888"
  application:
    name: apiserver
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: ['refresh','beans','env','info']

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka